import * as fs from "fs"
import * as crypto from "crypto"
import { Log } from "@/util/log"

const log = Log.create({ service: "sandbox-utils" })

export function isTarballHelperUpToDate(src: string, dst: string): boolean {
  try {
    const srcStat = fs.statSync(src)
    const dstStat = fs.statSync(dst)
    if (!srcStat.isFile() || !dstStat.isFile() || srcStat.size !== dstStat.size) return false
    return fs.readFileSync(src).equals(fs.readFileSync(dst))
  } catch {
    return false
  }
}

/**
 * Verify a helper binary against a set of trusted SHA-256 hashes.
 *
 * When `trustedHashes` is populated:
 *   - Computes SHA-256 of the binary once, then compares against every
 *     entry with constant-time comparison.
 *   - Returns true on first match, false if no entry matches.
 *
 * When `trustedHashes` is EMPTY (pre-release or source-deploy state):
 *   - Runs minimum plausibility checks instead of unconditionally blocking.
 *   - Checks: (1) file is readable, (2) file is at least 1KB (not a stub),
 *     (3) file has execute permission on Unix (skipped on Windows).
 *   - Returns true with a log.info if all checks pass.
 *   - Returns false with log.warn if any check fails.
 *
 * Hash map keys are forward-slash paths (generated by CI on Linux).
 * This function iterates Object.values() and compares only hash digests,
 * so key format does not affect verification. If key-based lookup is ever
 * added, normalize the lookup key with normalizeSlashes() first.
 *
 * This mirrors the graceful-degradation pattern in verifyBwrapHash,
 * making the sandbox usable without waiting for the CI hash pipeline.
 */
export function verifyHelperHash(binaryPath: string, trustedHashes: Record<string, string>): boolean {
  // When hashes are available: standard constant-time verification.
  if (Object.keys(trustedHashes).length > 0) {
    let digest: string
    try {
      const hash = crypto.createHash("sha256")
      hash.update(fs.readFileSync(binaryPath))
      digest = hash.digest("hex")
    } catch {
      return false
    }
    for (const trustedHash of Object.values(trustedHashes)) {
      if (!trustedHash || trustedHash.length === 0) continue
      if (digest.length !== trustedHash.length) continue
      let result = 0
      for (let i = 0; i < digest.length; i++) {
        result |= digest.charCodeAt(i) ^ trustedHash.charCodeAt(i)
      }
      if (result === 0) return true
    }
    return false
  }

  // Graceful degradation: no trusted hashes available.
  // Run minimum plausibility checks so source-deploy and pre-release
  // users can use the sandbox without waiting for CI hash population.
  log.info("Helper hash table is empty (pre-release/source-deploy) — running minimum plausibility checks", {
    path: binaryPath,
  })

  try {
    const stat = fs.statSync(binaryPath)
    if (!stat.isFile()) {
      log.warn("Helper binary is not a regular file — refusing to trust", { path: binaryPath })
      return false
    }
    // Minimum size: even a release-optimized Rust binary is > 1MB.
    // This catches stubs, shell scripts, and corrupted downloads.
    if (stat.size < 1024) {
      log.warn("Helper binary is too small — refusing to trust", { path: binaryPath, size: stat.size })
      return false
    }
    // Verify execute permission on Unix; skip on Windows (X_OK is not meaningful).
    if (process.platform !== "win32") {
      try {
        fs.accessSync(binaryPath, fs.constants.X_OK)
      } catch {
        log.warn("Helper binary is not executable — refusing to trust", { path: binaryPath })
        return false
      }
    }
    log.info("Helper binary passed minimum plausibility checks", { path: binaryPath, size: stat.size })
    return true
  } catch {
    log.warn("Cannot stat helper binary — refusing to trust", { path: binaryPath })
    return false
  }
}
